[package]
authors = [ "Maxime <salty-max> Blanc <max@jellycat.fr>" ]
autoexamples = false
categories = [ "parser-implementations", "parsing", "text-editors" ]
description = "Parser for gero-lang"
edition = "2024"
keywords = [ "incremental", "parsing", "tree-sitter", "gero-lang" ]
license = "MIT"
name = "tree-sitter-gero-lang"
readme = "README.md"
repository = "https://github.com/salty-max/tree-sitter-gero-lang"
version = "0.1.0"

build = "bindings/rust/build.rs"
include = [ "bindings/rust/*", "grammar.js", "queries/*", "src/*", "tree-sitter.json", "/LICENSE" ]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.27.0"
